# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0492cb5fc783cf498498f21cd876b0497fe427059c61a287de12f9d468a253f331ec92c56720145eec7e78744c0263e30c4337c9c86aa315b3ec9950c80172d0

test:
  secret_key_base: 8cde5da6866db4c512e8ea5964fa87fd14053e39b451c699fb7428bf5e40fb6b917079aacdc6491009381e1075dc1319e206edf92dd8a2d858b57dcefd46a0a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
